### ISSUE TITLE
Register (multiple) trees is broken 

### ISSUE THREAD

**Issue by norbertschuler** [Plant-for-the-Planet-org/treecounter-app#2119]
**Describe the bug**
The form submits, but show’s again without error and no trees are registered. 

**Is it on a Production or Development Build?**
production 

**To Reproduce**
1. Go to ‚Register multiple trees'
2. Fill in number of trees, name and choose position 
3. Click ‚register tree'

**Comment by norbertschuler** [comment]
I just tested registering a single tree and it also failed with a simple message `error`:

![F31F1736-D3B1-4FAA-9AFB-C83BDB4B4B3A](https://user-images.githubusercontent.com/1532418/78416727-32838800-7655-11ea-8add-a3bdb8472f01.png)

**Comment by mahmed0715** [comment]
on it.

**Comment by norbertschuler** [comment]
Trying to delete the single registered tree from the live server fails with error 500: `"Argument 1 passed to App\\Service\\AuthenticatedUserContext::matchTreecounter() must be an instance of App\\Entity\\Treecounter, instance of App\\Entity\\PlantContribution given, called in /app/src/CommandBus/Treecounter/Handler/TreecounterDeleteHandler.php on line 48"`

@jmiridis this is a backend error I think?

**Comment by jmiridis** [comment]
This should be fixed now.

**Comment by norbertschuler** [comment]
> on it.

@mahmed0715 have you been able to identify the problem and write a patch?

**Comment by mahmed0715** [comment]
Jorgo said he fixed it on backend.

**Comment by norbertschuler** [comment]
> Jorgo said he fixed it on backend.

No, he fixed the problem of deleting a tree again. The initial error isn’t fixed. My fault I added another error to this issue.

**Comment by mahmed0715** [comment]
I went and saw the the form was not handled by react. When submitted it posting to the base url that is shown on addressbar. Will check.

**Comment by norbertschuler** [comment]
Found a bug showing only for a millisecond (or if you shift-press the register button to open the result in another window):

```javascript
index.js:145 Uncaught TypeError: Cannot read property 'getValue' of null
    at RegisterTrees.onSubmitClick (index.js:145)
    at PrimaryButton._react.default.createElement.onClick (PrimaryButton.js:12)
```

**Comment by norbertschuler** [comment]
> I went and saw the the form was not handled by react. When submitted it posting to the base url that is shown on addressbar. Will check.

@mahmed0715 I think I fixed it now. Maybe you like to review my linked PR?
